FROM --platform=arm64 neilk3/splinterdb-build-env as build

RUN apt-get update -y \
    && apt-get install -y cmake zlib1g-dev \
    && apt-get clean

ENV CC clang
ENV CXX clang++-13
ENV LD clang++-13
ENV LIBS_DIR /work/libs/
ENV LD_LIBRARY_PATH ${LIBS_DIR}

COPY third-party/nuraft /work/nuraft
WORKDIR /work/nuraft/build
RUN cmake -DDISABLE_SSL=1 ../ \
    && make \
    && mkdir -p ${LIBS_DIR} \
    && cp /work/nuraft/build/libnuraft* ${LIBS_DIR}

WORKDIR /work/build