FROM --platform=arm64 neilk3/splinterdb-build-env

RUN apt-get update -y \
    && apt-get install -y cmake zlib1g-dev \
    && apt-get clean

ENV CC clang
ENV CXX clang++-13
ENV LD clang++-13

COPY third-party/nuraft /work/nuraft
WORKDIR /work/nuraft/build
RUN cmake -DDISABLE_SSL=1 ../ && make

COPY third-party/splinterdb /work/splinterdb
WORKDIR /work
COPY apps apps
COPY docker/CMakeLists.txt CMakeLists.txt

WORKDIR /work/build
RUN cmake ..

# WORKDIR /work/splinterdb