FROM --platform=arm64 neilk3/splinterdb-build-env

RUN apt-get update -y \
    && apt-get install -y cmake zlib1g-dev \
    && apt-get clean

ENV CC clang
ENV CXX clang++-13
ENV LD clang++-13
ENV LIBS_DIR /work/libs/
ENV LD_LIBRARY_PATH ${LIBS_DIR}

COPY third-party/nuraft /work/nuraft
WORKDIR /work/nuraft/build
RUN cmake -DDISABLE_SSL=1 ../ \
    && make \
    && mkdir -p ${LIBS_DIR} \
    && cp /work/nuraft/build/libnuraft* ${LIBS_DIR}

COPY third-party/splinterdb /work/splinterdb
WORKDIR /work/splinterdb
RUN make BUILD_VERBOSE=1 LIBDIR=${LIBS_DIR}

WORKDIR /work/build
COPY include /work/include
COPY apps /work/apps
COPY src /work/src
COPY docker/CMakeLists.txt /work/CMakeLists.txt
RUN cmake .. && make