#!/usr/bin/env bash

set -e

bash -c "cd /work/splinterdb && make BUILD_VERBOSE=1 LIBDIR=${LIBS_DIR} ${LIBS_DIR}/libsplinterdb.so"

cmake -DDISABLE_SSL=1 .. && make
EXIT_CODE=$?

echo "Build finished with code $EXIT_CODE"

exit $EXIT_CODE